In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([3, 2, 1])
a + b

tensor([4, 4, 4])

In [3]:
d = np.array([1, 2, 3])
e = torch.from_numpy(d)
e

tensor([1, 2, 3])

In [4]:
t = torch.rand(2,3)
t

tensor([[0.9447, 0.9084, 0.9779],
        [0.5535, 0.5628, 0.4201]])

In [5]:
a = torch.rand(2,3)
b = torch.rand(2,3)
a, b

(tensor([[0.2001, 0.7323, 0.1075],
         [0.8299, 0.8436, 0.1871]]),
 tensor([[0.4576, 0.4527, 0.5752],
         [0.9639, 0.2027, 0.1416]]))

In [7]:
b.add_(a)
b

tensor([[0.8579, 1.9174, 0.7902],
        [2.6237, 1.8899, 0.5158]])

In [14]:
f = torch.rand(4,4)
f

tensor([[0.3863, 0.3219, 0.6564, 0.2710],
        [0.5540, 0.2748, 0.4293, 0.4679],
        [0.5235, 0.2710, 0.3611, 0.4989],
        [0.0207, 0.3012, 0.0569, 0.6975]])

In [15]:
y = f.view(16)
y

tensor([0.3863, 0.3219, 0.6564, 0.2710, 0.5540, 0.2748, 0.4293, 0.4679, 0.5235,
        0.2710, 0.3611, 0.4989, 0.0207, 0.3012, 0.0569, 0.6975])

In [16]:
y = f.view(-1, 8)
y

tensor([[0.3863, 0.3219, 0.6564, 0.2710, 0.5540, 0.2748, 0.4293, 0.4679],
        [0.5235, 0.2710, 0.3611, 0.4989, 0.0207, 0.3012, 0.0569, 0.6975]])

In [17]:
y = f.view(2, -1)
y

tensor([[0.3863, 0.3219, 0.6564, 0.2710, 0.5540, 0.2748, 0.4293, 0.4679],
        [0.5235, 0.2710, 0.3611, 0.4989, 0.0207, 0.3012, 0.0569, 0.6975]])

In [18]:
x = torch.ones(8)
y = x.numpy()
x,y

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [19]:
x.add_(1)

tensor([2., 2., 2., 2., 2., 2., 2., 2.])

In [20]:
y

array([2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32)

In [21]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [22]:
x.to(device)
x

tensor([2., 2., 2., 2., 2., 2., 2., 2.])

In [23]:
x.to("cpu")

tensor([2., 2., 2., 2., 2., 2., 2., 2.])

In [24]:
#autograd

In [37]:
x = torch.ones(8, requires_grad=True)
y = x + 5 # +
c = y * y * 2 #*
d = c - 0.1 #-
#e = d.mean() #mean
e = torch.tensor([0.1, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0], dtype=torch.float32)

d.backward(e)

In [38]:
x.grad

tensor([  2.4000,  24.0000,  48.0000,  72.0000,  96.0000, 120.0000, 144.0000,
        168.0000])

In [ ]:
x.requires_grad(False)
x.detach()
with torch.no_grad():
  y = x + 5

with torch.inference_mode():
  y = x + 5

In [47]:
w1 = torch.ones(5, requires_grad=True)

epochs = 5

for epoch in range(epochs):
  x = (w1 * 3).sum()
  x.backward()
  print(w1.grad)
  w1.grad.zero_()


tensor([3., 3., 3., 3., 3.])
tensor([3., 3., 3., 3., 3.])
tensor([3., 3., 3., 3., 3.])
tensor([3., 3., 3., 3., 3.])
tensor([3., 3., 3., 3., 3.])
